[[main]]
  name = "Home"
  pageRef = "/"
  weight = 5

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 30

[[main]]
  name = "Consulting"
  url = "https://whiteboxml.com"
  weight = 40
  [main.params]
    external = true

